### ISSUE TITLE
Minecraft crash with Hudium

### ISSUE THREAD

**Issue by H4XKER** [Prismwork/Hudium#14]
my minecraft have mod called universal gravestone and whenever i try to go nearby gravestone it crash good thing i have not enough crash mod so i will include some log from not enough crash and hudium i use is on singleplayer world. i use the latest hudium for MC 1.19 hudium 1.4.0

minecraft universal gravestone mod:
https://www.curseforge.com/minecraft/mc-mods/universal-graves

from not enough crash: 
https://crashy.net/no8CN2EZw5R7umFgN4ia

from minecraft crash report:

---- Minecraft Crash Report ----
// My bad.

Time: 7/6/22, 11:19 AM
Description: Unexpected error

java.util.NoSuchElementException: No value present
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at java.util.Optional.get(Optional.java:143)
	at dev.intelligentcreations.hudium.client.gui.PlayerHud.renderBlockInfo(PlayerHud.java:113)
	at net.minecraft.client.gui.hud.InGameHud.handler$can000$onRender(InGameHud:4550)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:411)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:862)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1143)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Optional.get(Optional.java:143)
	at dev.intelligentcreations.hudium.client.gui.PlayerHud.renderBlockInfo(PlayerHud.java:113)
	at net.minecraft.class_329.handler$can000$onRender(class_329.java:4550)
	at net.minecraft.class_329.method_1753(class_329.java:411)

-- Affected level --
Details:
	All players: 1 total; [class_746['H4xKER'/208, l='ClientLevel', x=-163.45, y=79.00, z=234.47]]
	Chunk stats: 1024, 394
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,68,0), Section: (at 0,4,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 7260 game time, 7260 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:758)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, charmonium/journeyman

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1377820968 bytes (1313 MiB) / 3309305856 bytes (3156 MiB) up to 6316621824 bytes (6024 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 9
	Microarchitecture: unknown
	Frequency (GHz): 2.71
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) HD Graphics 620
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x5916
	Graphics card #0 versionInfo: DriverVersion=22.20.16.4836
	Graphics card #1 name: NVIDIA GeForce 940MX
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 2048.00
	Graphics card #1 deviceId: 0x134d
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7219
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 14989.22
	Virtual memory used (MB): 8856.06
	Swap memory total (MB): 2816.00
	Swap memory used (MB): 0.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx6024m
	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.1
		adorn: Adorn 3.5.4+1.19
		amazingchest: Amazing Chest 0.0.7+1.19
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.7.28
		autoclicker-fabric: Auto Clicker 1.19-1.4.0-build.17
		badpackets: Bad Packets 0.1.2
		bettersculk: Better Sculk 1.0.0-1.19
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.8.2
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.8.2
			c2me-client-uncapvd: Concurrent Chunk Management Engine (Client/Uncap View Distance) 0.2.0+alpha.8.2
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.8.2
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.8.2
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.8.2
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.8.2
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.8.2
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.8.2
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.8.2
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.8.2
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.8.2
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.8.2
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.8.2
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.8.2
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.8.2
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.8.2
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.8.2
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.8.2
			c2me-threading-scheduling: Concurrent Chunk Management Engine (Threading/Scheduling) 0.2.0+alpha.8.2
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.8.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			com_ibm_async_asyncutil: asyncutil 0.1.0
			org_threadly_threadly: threadly 7.0
		camsbackpacks: Cammie's Wearable Backpacks 2.12
		charm: Charm 4.1.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmonium: Charmonium 4.1.0
		chunky: Chunky 1.2.217
		clear-skies: Clear Skies 2.0.94
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 2.0.0+1.19
		dashloader: DashLoader 4.0.0+1.19
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		deathlog: DeathLog 0.2.10+1.19
		diggusmaximus: Diggus Maximus 1.5.6-1.19
			kyrptconfig: Kyrpt Config 1.4.6-1.19
				blue_endless_jankson: jankson 1.2.1
		dungeons_arise: When Dungeons Arise 2.1.51
		earthbounds: Earthbounds 1.19-1.1.3
		eatinganimationid: Eating Animation 1.8.1
		editsign: EditSign 2.4.1
		expandeddelight: Expanded Delight 0.2
		fabric: Fabric API 0.57.0+1.19
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricenchantments: Fabric Enchantments 0.8.0
		fabricloader: Fabric Loader 0.14.8
		fallingtree: FallingTree 3.6.1
		farmersdelight: Farmer's Delight 1.19-0.3.0
		firstperson: FirstpersonModel 2.1.0
		forgeconfigapiport: Forge Config API Port 4.0.0
		fwaystones: Fabric Waystones 3.0.0
		geckolib3: Geckolib 3.1.5
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		healthcare: Health Care 1.1.0
			config2brigadier: Config to Brigadier 1.1.4
		highlighter: Highlighter 1.1.2
		hudium: Hudium 1.4.0+mc1.19
			omega-config: OmegaConfig 1.3-1.19-pre5
			spruceui: SpruceUI 4.0.0+1.19
		iceberg: Iceberg 1.0.38
		indium: Indium 1.0.6+mc1.19
		inventorymanagement: Inventory Management 1.0.1
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.1.2+1.19
			pride: Pride Lib 1.1.2+1.19
		lazydfu: LazyDFU 0.1.3
		legendarytooltips: Legendary Tooltips 1.2.6
		mcg: MCG 1.2.7
		memoryleakfix: memory Leak Fix 1.19-0.4.1
		minecartbooster: Minecart Booster 0.1.1
		minecraft: Minecraft 1.19
		mining_helmet: Mining Helmet 1.1.1+1.19
		mob_catcher: Mob Catcher 1.2.2
		modern_industrialization: Modern Industrialization 1.3.0-beta
			magna: Magna 1.8.0-1.19
			noindium: No Indium? 1.0.2+1.18.2
			patchouli: Patchouli 1.19-70-FABRIC-SNAPSHOT
				fiber: fiber 0.23.0-2
			playerabilitylib: Pal 1.6.0
			team_reborn_energy: Energy 2.2.0
		modmenu: Mod Menu 4.0.0
		moremusic: More Music 0.1.3+1.19
		mousetweaks: Mouse Tweaks 2.22
		notenoughanimations: NotEnoughAnimations 1.6.0
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		openmcskins: OpenMCSkins 1.3.6
		reeses-sodium-options: Reese's Sodium Options 1.4.3+mc1.19-build.43
		right-click-harvest: Right-Click-Harvest 1.2.0
		roughlyenoughitems: Roughly Enough Items 9.1.500
		roughlyenoughprofessions: Roughly Enough Professions 1.1.0
		rpgstats: RPGStats 4.3.15+1.19
			autoconfig1u: Auto Config v1 Updated 3.4.0
			cardinal-components-base: Cardinal Components API (base) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		seasons: Fabric Seasons 1.4-BETA+1.19
		sleepwarp: SleepWarp 1.2.0+1.19
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.5+mc1.19-build.43
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		sound_physics_remastered: Sound Physics Remastered 1.19-1.0.6
		spark: spark 1.9.13
		starlight: Starlight 1.1.1+fabric.ae22326
		t_and_t: Towns and Towers - Structure Add-on 1.7
		trade_cycling: Trade Cycling 1.19-1.0.2
		universal-graves: Universal Graves 2.1.0+1.19
			common-protection-api: Common Protection API 1.0.0
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			hologram-api: Hologram API 0.2.2+1.19
			placeholder-api: Placeholder API 2.0.0-beta.6+1.19
			polymer: Polymer (Core) 0.2.2+1.19
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.1+1.19
			server_translations_api: Server Translations API 1.4.16+1.19
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
			sgui: sgui 1.1.1+1.19
		wildfire_gender: Wildfire's Female Gender Mod 1.19-3.0.0
		worldtime: WorldTime 1.19-fabric0.53.3-1.3.1
			crowdin-translate: CrowdinTranslate 1.4+1.19
			gbfabrictools: GBfabrictools 1.3.4+1.19
		wthit: wthit 5.5.1
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce 940MX/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.19, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fast
	Resource Packs: Fabric Mods, charmonium/journeyman
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['H4xKER'/208, l='ServerLevel[New World]', x=-163.45, y=79.00, z=234.47]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Client Crashes Since Restart: 1
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Hudium (hudium)

**Comment by moechakucha** [comment]
seems that block info does not know how to deal with polymer custom blocks (like the grave).
Gotta need some hacky ways to fix that :) i'll look into it a bit
